<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>¿Quiénes somos?</h3>
      <p>Un grupo de personas, mujeres y hombres, empresarios y directivos, españoles e ingleses, que a través de nuestras relaciones personales y empresariales hemos constatado el déficit mayoritario de los que incluso trabajamos en inglés, para relacionarnos
        y vivir en inglés de forma natural.</p>
      <p>Para muchos de nosotros hablar inglés es un esfuerzo e implica un estado de continua tensión, pero todos querríamos vivirlo de manera gratificante como lo hacemos en nuestra lengua nativa.</p>
      <p>Algunos tenemos el propósito de hacer cursos de aprendizaje o mejora pero nos falta tiempo o recursos económicos y desde luego no nos lo planteamos como un tiempo de diversión y relax.</p>
      <p>Por todo ello, en Sexy English comenzamos a trabajar en nuevas formas de aprendizaje, y por qué no, volver a ser niños, a jugar y aprender desde el punto de vista de nuestros instintos y emociones, sobre una base de contenidos adultos. En definitiva,
        plantear temas divertidos que a todos nos interesan, y crear nuestro propio método.</p>
      <p>Nuestro grupo suma experiencias varias, más de treinta años de experiencia en la enseñanza de inglés y …. más de veinte años de experiencia en el aprendizaje… y si les digo la verdad, yo… que soy parte de Sexy English, voy a ser su alumna más interesada…
        ¡Estoy deseando empezar el curso!</p>
      <div class="btn boton btn-claro">Quiero saber más</div>
    </div>
    <div class="col-md-6">
      <div class="hover-scape">
        <img src="static/img/img-iphone.png" alt="" class="img-iphone" />
        <img src="static/img/img-ipad.png" alt="" class="img-ipad" />
      </div>
    </div>
  </div>
</div>