<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>¿Qué quiere el alumno de inglés</h3>
      <p>Cuántos hemos hecho cursos de inglés, basados en la repetición de frases que no nos interesaban: a quién le importa si el lápiz es azul o rojo o si el perro está lejos o cerca, o si la silla está al lado o detrás de una pared… lo hemos intentado,
        muchos hemos aprendido con sufrimiento, en nuestros trabajos, en clases aburridas después del trabajo, en casa… Otros nunca lo han conseguido, pero si quieren y vuelven a planteárselo… pueden conseguirlo ahora con Sexy English.</p>
      <p>Con Sexy English podremos con el tiempo mantener una reunión en inglés, leer documentos o escribir un mail, pero la vida es algo más, y podremos compartir una agradable velada, leer ese libro que tanto nos gustó, disfrutar de la película de moda
        en versión original, entender las canciones que nos enamoran y por qué no, seducir, divertir y divertirnos, tener amigos de habla inglesa y poder hablar de lo que nos preocupa, entender y pensar en su lengua, y quizás algo más…</p>
      <p>La mayoría no lo hemos conseguido y navegamos en el proceloso mar de la inseguridad… sonrisas inexpresivas cuando no entendemos o lo peor, poner cara de “no se lo que me dicen…” y mantenernos silenciosos, como si no tuviéramos nada que decir.</p>
      <div class="btn boton btn-claro">Quiero saber más</div>
    </div>
    <div class="col-md-6">
      <div class="hover-scape">
        <img src="static/img/img-iphone.png" alt="" class="img-iphone" />
        <img src="static/img/img-ipad.png" alt="" class="img-ipad" />
      </div>
    </div>
  </div>
</div>