<div id="upper-menu-mobile">
  <div id="page-menu-wrapper">
    <ul style="border: none; box-shadow: none;" class="main no-js">
      <li class="submenu-item">
        <a href="javascript:void(0)" class="top-menu">
          <label>¿Quieres que te invitemos?</label>
        </a>
      </li>
    </ul>
    <ul class="main right no-js">
      <li class="submenu-item">
        <a href="javascript:void(0)" class="top-menu">
          <label>Síguenos</label>
        </a>
        <div class="dropdown-menu follow">
          <ul class="social">
            <li><a href="http://feeds.feedburner.com/sexyenglish" target="_blank" title="Subscribe by RSS" class="rss">RSS</a>
            </li>
            <li><a href="http://www.twitter.com/sexyenglishlearning" target="_blank" title="Follow us on Twitter" class="twitter">Twitter</a>
            </li>
            <li><a href="http://www.facebook.com/sexyenglishlearning" target="_blank" title="Join us on Facebook" class="facebook">Facebook</a>
            </li>
            <li><a href="https://www.google.com/+sexyenglishlearning" target="_blank" title="Google+" class="googleplus">Google+</a>
            </li>
          </ul>
          <div class="counter">338194 suscriptores & seguidores</div>
        </div>
      </li>
    </ul>
  </div>
</div>
<div id="upper-menu-container">
  <div id="page-menu-wrapper">
    <ul class="main left no-js">
      <li>
        <a href="http://designmodo.com" class="top-menu home"></a>
      </li>
      <li class="submenu-item mobile-class"><a href="#" class="top-menu">Categories</a>
        <div class="dropdown-menu categories">
          <div class="menu-header">
            <ul id="menu-nav-menu-1" class="menu">
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-98952"><a href="http://designmodo.com/design/">Design</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18118"><a href="http://designmodo.com/freebies/">Freebies</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18124"><a href="http://designmodo.com/tutorials/">Tutorials</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-46154"><a href="http://designmodo.com/coding/">Coding</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18120"><a href="http://designmodo.com/inspiration/">Inspiration</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18125"><a href="http://designmodo.com/wordpress/">WordPress</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-79238"><a href="http://designmodo.com/resources/">Resources</a>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li><a href="http://designmodo.com/shop/" class="top-menu shop">Shop</a>
      </li>
      <li class="mobile-class">
        <div class="top-menu search"><span class="label">Search</span>
          <div class="formsearch">
            <form id="search" action="http://designmodo.com/search/" method="get" target="_top">
              <input name="q" type="text" class="search-input" />
              <input name="cx" type="hidden" value="partner-pub-8533961490949414:1129877839" />
              <input name="cof" type="hidden" value="FORID:10" />
              <input name="ie" type="hidden" value="UTF-8" />
            </form>
          </div>
        </div>
      </li>
    </ul>
    <ul style="float: right; right: -1px; position: relative;" class="main right no-js">
      <li class="submenu-item mobile-class"><a href="#" class="top-menu">Follow us</a>
        <div class="dropdown-menu follow">
          <ul class="social">
            <li><a href="http://feeds.feedburner.com/designmodo" target="_blank" title="Subscribe by RSS" class="rss">RSS</a>
            </li>
            <li><a href="http://www.twitter.com/designmodo" target="_blank" title="Follow us on Twitter" class="twitter">Twitter</a>
            </li>
            <li><a href="http://www.facebook.com/designmodo" target="_blank" title="Join us on Facebook" class="facebook">Facebook</a>
            </li>
            <li><a href="https://www.google.com/+DesignModo" target="_blank" title="Google+" class="googleplus">Google+</a>
            </li>
            <li><a href="http://dribbble.com/designmodo" target="_blank" title="Follow us on Dribbble" class="dribbble">Dribbble</a>
            </li>
          </ul>
          <div class="counter">338194 Subscribers & Followers</div>
        </div>
      </li>
      <li class="submenu-item mobile-class">
        <a href="javascript:void(0)" class="top-menu profile">
          <label>Fernando Guirao
          </label>
        </a>
        <div class="dropdown-menu profile">
          <div class="menu-header">
            <ul id="menu-profile-menu-1" class="menu">
              <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-92378"><a href="http://designmodo.com/my-account/">My Account</a>
              </li>
              <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-97151"><a href="http://designmodo.com/my-account/rewards/">Rewards</a>
              </li>
              <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-97148"><a href="http://designmodo.com/my-account/affiliate-program/">Affiliate
Program</a>
              </li>
              <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-97145"><a href="http://designmodo.com/my-account/log-out/">Log
Out</a>
              </li>
            </ul>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>
<div id="header-wrapper">
  <div id="logo">
    <a href="http://designmodo.com" title="Designmodo – Web Design and Development Magazine" class="main-logo"></a>
  </div>
</div>
<div id="main-wrapper">
  <script type="text/javascript">
  try
  {
    Typekit.load();
  }
  catch (e)
  {}
  </script>
  <div class="presenation">
    <section class="video">
      <div id="bgVideo" class="background"></div>
      <div class="holder">
        <div class="cont"><span class="sdf"><strong>Startup</strong>Design Framework</span><a href="https://vimeo.com/designmodo/startup" target="_blank" class="play"><span class="fui-play"></span></a><span class="suys"><strong>Suit Up</strong>your
Startup</span><a href="#overview" class="arrow"><span aria-hidden="true" class="icn_arrow"></span></a>
        </div>
      </div>
    </section>
    <section id="overview" class="simple-block">
      <div class="holder">
        <h3>We have created the product that will help designers, developers
and companies to create a website for their startups not spending
much time on it.</h3>
      </div>
    </section>
    <section id="topSlider-wrapper" class="features">
      <ul id="topSliderCtrl">
        <li><a data-slide-index="0">First</a>
        </li>
        <li><a data-slide-index="1">Second</a>
        </li>
        <li><a data-slide-index="2">Third</a>
        </li>
      </ul>
      <ul id="topSlider">
        <li>
          <section class="first">
            <div class="holder">
              <h1>Beautiful Framework</h1>
              <p>A high-quality solution for those who want to change their startup and not waste too much time.</p>
              <div class="item">
                <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon1.png" class="icon" />
                <h3>Block Model</h3>
                <p>You can easily combine any components in a variety of design projects. It’s easy!</p>
              </div>
              <div class="item">
                <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon2.png" class="icon" />
                <h3>Many Components</h3>
                <p>There are a lot of different components that will help you to make a perfect suit for your startup.</p>
              </div>
            </div>
          </section>
        </li>
        <li>
          <section class="second">
            <div class="holder">
              <h1>Ready to Code</h1>
              <p>Each component is coded for web which will sufficiently fasten the process of creating a website.</p>
              <div class="item">
                <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon3.png" class="icon" />
                <h3>HTML5, CSS3, LESS</h3>
                <p>We used checked-out technologies to give the best results.
                </p>
              </div>
              <div class="item">
                <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon4.png" class="icon" />
                <h3>Based on Bootstrap</h3>
                <p>HTML layout is based on one of the common and reliable frameworks at this time - Bootstrap v 2.3.2.</p>
              </div>
            </div>
          </section>
        </li>
        <li>
          <section class="third">
            <div class="holder">
              <h1>Perfect for Startups</h1>
              <p>Startup Framework will help you to find an awesome form for your startup project in a short time.</p>
              <div class="item">
                <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon5.png" class="icon" />
                <h3>Save Your Time</h3>
                <p>Use your time for generating new ideas for your startup. Take a break from the routine.</p>
              </div>
              <div class="item">
                <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon6.png" class="icon" />
                <h3>Money Economy</h3>
                <p>Startups can save money on design and code and spend it on concept and functionality.</p>
              </div>
            </div>
          </section>
        </li>
      </ul>
    </section>
    <section class="demo">
      <div class="holder">
        <div class="background">
          <div></div>
        </div>
        <div class="cont">
          <h1>Demo Version<span class="forksandstars"><iframe frameborder="0" scrolling="0" src="http://ghbtns.com/github-btn.html?user=designmodo&amp;repo=startup-demo&amp;type=watch&amp;count=true&amp;size=large" style="width: 90px; height: 30px; border: none;"><iframe frameborder="0" scrolling="0" src="http://ghbtns.com/github-btn.html?user=designmodo&amp;repo=startup-demo&amp;type=fork&amp;count=true&amp;size=large" style="width: 100px; height: 30px; border: none;"></iframe></iframe></span></h1>
          <p>We have created this demo version in order to show you the structure of Startup Framework. It has some of the components from the full version, 2 great samples and documentation. You can also find 2 images of a Macbook and an iPad, which you
            can use in your project. We hope you will like your first introduction to Startup Framework.
          </p><a href="http://designmodo.github.io/startup-demo" target="_blank" class="button">View
Demo on Github</a>
          <ul>
            <li>
              <h2>What is in this Demo?</h2>
              <p><strong>11</strong>Components</p>
              <p><strong>2</strong>Samples</p>
              <p><strong>2</strong>Pictures</p>
            </li>
            <li>
              <h2>What's in the Full Version?</h2>
              <p><strong>100</strong>Components</p>
              <p><strong>25</strong>Samples</p>
              <p><strong>14</strong>Pictures</p>
            </li>
          </ul>
        </div>
      </div>
    </section>
    <section class="dof">
      <div class="holder">
        <div class="cont"><span style="-webkit-filter: blur(5px); filter: blur(5px);" class="text-block">Focus on Design</span>
        </div>
      </div>
      <div class="background">
        <div class="cards layer1"></div>
        <div class="cards layer2"></div>
        <div class="cards layer3"></div>
      </div>
    </section>
    <section class="components">
      <div class="details">
        <div class="cont">
          <h1>Many Useful Components</h1>
          <p>Startup Design Framework contains components and complex blocks which can easily be integrated into almost any design. All of these components are made in the same style, and can easily be integrated into projects, allowing you to create hundreds
            of solutions for your future projects.</p>
        </div>
      </div>
      <div class="holder">
        <ul>
          <li class="first">
            <h3>Responsive Layout</h3>
            <p>Of course we haven’t forgotten about the responsive layout. Create a website with full mobile support.</p>
          </li>
          <li class="second">
            <h3>Clear Grid</h3>
            <p>Components and blocks fixed to common and popular 12 Grid system. It allows you to find understanding between the designer and developer.</p>
          </li>
          <li class="third">
            <h3>Retina Ready</h3>
            <p>Startup Framework works fine on devices supporting Retina Display. Feel the clarity in each pixel.</p>
          </li>
        </ul>
        <div id="component-grid" class="screenshots">
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-1.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-2.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-6.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-8.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-3.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-4.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-7.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-5.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-9.png" />
          </div>
        </div>
      </div>
    </section>
    <section class="samples">
      <div class="details">
        <div class="cont">
          <h1>Twenty Five Awesome Samples</h1>
          <p>The most important part of the Startup Framework is the samples. The samples form a set of 25 usable pages you can use as is or you can add new blocks from UI Kit. By choosing one of the 25 configurations of the future startup, the process of
            creation is simple and easy.</p>
        </div>
      </div>
      <div class="holder">
        <ul>
          <li class="first">
            <h3>Easy to use</h3>
            <p>To get started, you select the desired sample and base the entire website on it. It’s that simple!</p>
          </li>
          <li class="second">
            <h3>Variety of designs</h3>
            <p>You can decide whether to create your site using UI Kit blocks or samples. The blocks can merge together in various combinations.
            </p>
          </li>
          <li class="third">
            <h3>Feel our design</h3>
            <p>Samples will show you the feeling on how to play around using the components in the website building process.</p>
          </li>
        </ul>
        <div id="samples-grid" class="screenshots">
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-1.png" />
          </div>
          <div class="screen double">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-8.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-22.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-23.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-9.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-17.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-2.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-24.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-10.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-3.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-18.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-25.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-11.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-4.png" />
          </div>
          <div class="screen">img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-19.png" alt="" /></div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-26.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-12.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-5.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-13.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-27.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-20.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-6.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-21.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-14.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-7.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-15.png" />
          </div>
          <div class="screen">
            <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-16.png" />
          </div>
        </div>
      </div>
    </section>
    <section id="lastBlock-wrapper" class="lastBlock">
      <ul id="lastBlockCtrl">
        <li class="menuicon"><span aria-hidden="true" class="icn_menu"></span>
        </li>
        <li><a data-slide-index="0">Images</a>
        </li>
        <li><a data-slide-index="1">Documentation</a>
        </li>
        <li><a data-slide-index="2">Showcase</a>
        </li>
        <li><a data-slide-index="3">Information</a>
        </li>
      </ul>
      <ul id="lastSlider">
        <li>
          <section class="moreThanImage">
            <div class="holder">
              <div class="bg">
                <div class="pic1 visible"></div>
                <div class="pic2"></div>
                <div class="pic3"></div>
              </div>
              <div class="cont">
                <h1>More Than Image</h1>
                <p>We prepared some HQ photos that you can use in your startup projects. When you have to present app or website on iPhone, iPad or Macbook you can use these images. It’s a quick solution if you don’t have proper images ready to use.
                </p>
                <ul>
                  <li>
                    <h3>Smart Layers</h3>
                    <p>Just put the image with your App screen inside Smart Layer and get the photo.</p>
                  </li>
                  <li>
                    <h3>High Resolution</h3>
                    <p>We did a 2.5K size photo that will suit even for a very large site.</p>
                  </li>
                </ul>
                <div class="anthony">Photos for samples are made by<a href="http://photo.repponen.com/" target="_blank">Anton
Repponen</a>during his travels around the world. Contact him to purchase some photos.</div>
              </div>
            </div>
          </section>
        </li>
        <li>
          <section class="doc">
            <div class="holder">
              <div class="bg">
                <div></div>
              </div>
              <div class="cont">
                <h1>Documentation</h1>
                <p>Documentation is really important for a developer. Right from it you get to know the product. We tried to describe all the components, provide the set-up instructions and foresee most of the issues you may come across while working with
                  the framework.
                </p>
                <ul>
                  <li>
                    <h3>User Guide</h3>
                    <p>You’ll get a description of each component and learn how to connect and use them.</p>
                  </li>
                  <li>
                    <h3>Video Tutorials<span class="soon">Soon</span></h3>
                    <p>Video tutorials show you how to make a site from design to code.</p>
                  </li>
                </ul>
              </div>
            </div>
          </section>
        </li>
        <li>
          <section class="showcase">
            <div class="holder">
              <div class="bg">
                <div class="pic1 visible"></div>
                <div class="pic2"></div>
              </div>
              <div class="cont">
                <h1>Showcase</h1>
                <p>Two perfect examples of using framework - Crumbs and Hipsta Food. These guys have a passion for cooking food and they are really a good deal. We’ll be glad to have a look at your projects created on Startup Framework and show them to our
                  users.</p>
                <ul>
                  <li>
                    <a href="http://crumbs.am" target="_blank">
                      <img alt="Crumbs" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/bottomSlider/crumbs.png" /><b><strong>Crumbs</strong><span class="svgIcon"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="16" height="16" viewbox="0 0 32 32"><path d="M30 0h-16c-1.105 0-2 0.894-2 2v16c0 1.105 0.895 2 2 2h16c1.105 0 2-0.895 2-2v-16c0-1.105-0.895-2-2-2zM28 16h-12v-12h12v12zM16 28h-12v-12h4v-4h-6c-1.105 0-2 0.895-2 2v16c0 1.105 0.894 2 2 2h16c1.105 0 2-0.895 2-2v-6h-4v4z" fill="#eaeaea"></path></svg></span></b><span>Fresh food, delicious desserts, artisan breads and
cozy atmosphere. All at one place.</span>
                    </a>
                  </li>
                  <li>
                    <a href="http://hipstafood.com/" target="_blank">
                      <img alt="Hipstafood" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/bottomSlider/hipstafood.png" /><b><strong>Hipstafood</strong><span class="svgIcon"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="16" height="16" viewbox="0 0 32 32"><path d="M30 0h-16c-1.105 0-2 0.894-2 2v16c0 1.105 0.895 2 2 2h16c1.105 0 2-0.895 2-2v-16c0-1.105-0.895-2-2-2zM28 16h-12v-12h12v12zM16 28h-12v-12h4v-4h-6c-1.105 0-2 0.895-2 2v16c0 1.105 0.894 2 2 2h16c1.105 0 2-0.895 2-2v-6h-4v4z" fill="#eaeaea"></path></svg></span></b><span>Handy
iPhone App preparing for the launch will show you recipes
and teach you to cook.</span>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </section>
        </li>
        <li>
          <section class="info">
            <div class="holder">
              <div id="subMenuWrapper">
                <div class="submenu">
                  <div></div>
                  <ul id="subMenuCtrl">
                    <li><span class="selected">Technical
Information</span>
                    </li>
                    <li><span>Press Release</span>
                    </li>
                    <li class="faq-u"><span>F.A.Q.</span>
                    </li>
                  </ul>
                </div>
                <ul id="subMenu">
                  <li class="active">
                    <div class="cont">
                      <h1>Technical Information</h1>
                      <p>We will be glad to solve your questions. We want to make our product better and very soon we will release some cool updates for you.</p>
                      <div><a href="https://github.com/designmodo/startup-support/issues" target="_blank" class="ask">Ask a Question</a>
                      </div>
                      <dl class="tech-info"><dt>Release Date</dt>
                        <dd class="clearfix">December 16, 2013</dd><dt>Format</dt>
                        <dd class="clearfix">PSD, HTML, CSS, JS, LESS</dd><dt>Size</dt>
                        <dd class="clearfix">637 MB, Zip</dd><dt>Consists</dt>
                        <dd class="clearfix">Components
                          <br/>25 Samples
                          <br/>Photos</dd><dt>Bootstrap Version</dt>
                        <dd class="clearfix">2.3.2</dd><dt>License</dt>
                        <dd class="clearfix"><a href="http://designmodo.com/startup-license" target="_blank">Commercial License</a>
                        </dd><dt>Updates</dt>
                        <dd class="clearfix">Free</dd>
                      </dl>
                    </div>
                  </li>
                  <li>
                    <div class="cont">
                      <h1>Press Release</h1>
                      <p>In case you’ve decided to write about our project on your blog you can use this press release. Here you can find all necessary information about Startup Framework: project description, images that you can use while writing articles,
                        and also banners and information about our affiliate program.</p>
                      <p><a href="http://designmodo.com/startup-press-release" target="_blank">Open Press Release</a>
                      </p>
                      <div><a href="mailto:info@designmodo.com?subject=Hello!" class="ask">Contact
Us</a>
                      </div>
                    </div>
                  </li>
                  <li>
                    <div class="cont faqiframe">
                      <h1>F.A.Q.</h1>
                      <object data="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/faq.html" type="text/html" width="100%"></object>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </section>
        </li>
      </ul>
    </section>
    <section class="purchase">
      <div class="holder">
        <h1>Get Startup Framework</h1><a href="/startup/?add-to-cart=109981" class="button">Purchase for $249</a><span>PSD + HTML<b>Full Version</b><strong><a href="http://designmodo.com/startup-license" target="_blank">Commercial
License</a></strong></span>
      </div>
    </section>
    <section class="social">
      <div class="holder"></div>
    </section>
  </div>
  <!--<COMMENTS>CONTAINER START HERE </COMMENTS>-->
  <div style="clear: both;"></div>
  <div id="content-wrapper">
    <div style="clear: both;"></div>
    <div style="display: none;" class="articles-container">
      <div>
        <div style="clear: both;"></div>
      </div>
      <!--<end>article-single</end>-->
      <div style="clear: both;"></div>
      <div class="comments-wrapper">
        <h1 class="startup-comments-title">Discussion<span><a href="#respond">Leave a comment</a></span></h1>
      </div>
      <!--<end>articles container</end>-->
      <div style="clear: both;"></div>
    </div>
    <!--<end>content-wrapper</end>-->
  </div>
  <!--<end>main-wrapper </end>-->
  <div id="footer-wrapper">
    <div class="menu-footer-container">
      <ul id="menu-footer-menu" class="page-menu-wrapper-footer">
        <li id="menu-item-89205" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89205"><a href="http://designmodo.com/privacy-statement/">Privacy</a>
        </li>
        <li id="menu-item-89206" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89206"><a href="http://designmodo.com/terms-and-conditions/">Terms</a>
        </li>
        <li id="menu-item-89204" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89204"><a href="http://designmodo.com/advertise/">Advertise</a>
        </li>
        <li id="menu-item-89605" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89605"><a href="http://designmodo.com/affiliates/">Affiliates</a>
        </li>
        <li id="menu-item-98791" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-98791"><a href="http://designmodo.com/subscribe/">Newsletter</a>
        </li>
        <li id="menu-item-89207" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89207"><a href="http://designmodo.com/about/">About</a>
        </li>
        <li id="menu-item-102718" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-102718"><a href="http://journal.designmodo.com/">Journal</a>
        </li>
        <li id="menu-item-89209" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89209"><a href="http://designmodo.com/contact-us/">Contact Us</a>
        </li>
      </ul>
    </div>
    <ul id="footer-container-right">
      <li class="copyright">Copyright © 2013<a href="http://designmodo.com/" title="DesignModo" class="on">Designmodo</a>. All Rights Reserved.
      </li>
      <li class="copyright">
        <div><a href="http://www.dmca.com/Protection/Status.aspx?ID=e4da61dc-6d57-4588-a701-a53419f71fa6" title="DMCA">DMCA Protected</a>•<a href="http://www.mediatemple.net/" target="_blank" title="MediaTemple">Hosted by MediaTemple</a>
        </div>
      </li>
    </ul>
  </div>
</div>