<div id="footer-wrapper">
  <div class="menu-footer-container">
    <ul id="menu-footer-menu" class="page-menu-wrapper-footer">
      <li id="menu-item-89205" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89205"><a href="http://designmodo.com/privacy-statement/">Privacy</a>
      </li>
      <li id="menu-item-89206" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89206"><a href="http://designmodo.com/terms-and-conditions/">Terms</a>
      </li>
      <li id="menu-item-89204" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89204"><a href="http://designmodo.com/advertise/">Advertise</a>
      </li>
      <li id="menu-item-89605" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89605"><a href="http://designmodo.com/affiliates/">Affiliates</a>
      </li>
      <li id="menu-item-98791" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-98791"><a href="http://designmodo.com/subscribe/">Newsletter</a>
      </li>
      <li id="menu-item-89207" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89207"><a href="http://designmodo.com/about/">About</a>
      </li>
      <li id="menu-item-102718" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-102718"><a href="http://journal.designmodo.com/">Journal</a>
      </li>
      <li id="menu-item-89209" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89209"><a href="http://designmodo.com/contact-us/">Contact Us</a>
      </li>
    </ul>
  </div>
  <ul id="footer-container-right">
    <li class="copyright">Copyright © 2013<a href="http://designmodo.com/" title="DesignModo" class="on">Designmodo</a>. All Rights Reserved.
    </li>
    <li class="copyright">
      <div><a href="http://www.dmca.com/Protection/Status.aspx?ID=e4da61dc-6d57-4588-a701-a53419f71fa6" title="DMCA">DMCA Protected</a>•<a href="http://www.mediatemple.net/" target="_blank" title="MediaTemple">Hosted by MediaTemple</a>
      </div>
    </li>
  </ul>
</div>