<div id="footer-wrapper">
  <div class="menu-footer-container">
    <ul id="menu-footer-menu" class="page-menu-wrapper-footer">
      <li id="menu-item-98791" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-98791"><a href="#" class="show-suscribe">Newsletter</a>
      </li>
      <li id="menu-item-89209" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-89209"><a href="mailto:hello@sexy-english.com">Contacto</a>
      </li>
    </ul>
  </div>
  <ul id="footer-container-right">
    <li class="copyright">Copyright ©2013 <a href="http://sexy-english.com/" title="Sexy English" class="on">Sexy English</a>. Todos los derechos reservados.</li>
  </ul>
</div>
<audio autoplay="autoplay">
  <source src="custom-pages/sexyenglish/common-files/media/sexy.mp3" />
  <source src="custom-pages/sexyenglish/common-files/media/sexy.ogg" />
</audio>