<link id="dm_style-css" href="style.css" media="all" rel="stylesheet" type="text/css" />
<link id="dm_shop_startup_bxslider-css" rel="stylesheet" href="custom-pages/sexyenglish/presentation/bxslider/jquery.bxslider.css" type="text/css" media="all" />
<link id="dm_shop_startup_icon_fonts-css" href="custom-pages/sexyenglish/common-files/css/icon-font.css" media="all" rel="stylesheet" type="text/css" />
<link id="dm_shop_startup_style-css" href="custom-pages/sexyenglish/presentation/css/all.css" media="all" rel="stylesheet" type="text/css" />
<link id="font-awesome" href="custom-pages/sexyenglish/common-files/css/font-awesome.css" media="all" rel="stylesheet" type="text/css" />
<link id="sexy_style-css" href="css/app.css" media="all" rel="stylesheet" type="text/css" />
<script src="js/jquery/jquery.js?ver=1.10.2" type="text/javascript"></script>
<script src="js/jquery/jquery-migrate.min.js?ver=1.2.1" type="text/javascript"></script>
<script src="js/mobile-nav.js?ver=1.0" type="text/javascript"></script>
<script src="js/modernizr.custom.79881.js" type="text/javascript"></script>
<script src="js/common.js?t=1387781093" type="text/javascript"></script>
<script src="js/jquery/jquery-1.8.3.min.js" type="text/javascript"></script>
<script src="custom-pages/sexyenglish/presentation/js/jquery.backgroundvideo.min.js" type="text/javascript"></script>
<script src="custom-pages/sexyenglish/presentation/js/all.js" type="text/javascript"></script>
<script src="custom-pages/sexyenglish/presentation/bxslider/jquery.bxslider.min.js" type="text/javascript"></script>
<script src="custom-pages/sexyenglish/presentation/js/masonry.pkgd.min.js" type="text/javascript"></script>
<script src="custom-pages/sexyenglish/presentation/js/polyfill.requestAnimationFrame.js" type="text/javascript"></script>
<script src="custom-pages/sexyenglish/presentation/js/jquery.sharrre.min.js" type="text/javascript"></script>