<!DOCTYPE html>
<html lang="es">
  <head>
    <?php include 'views/head-meta.phtml' ?>
    <?php include 'views/head-statics.phtml' ?>
  </head>
  <body>
    <div class="presenation">
      <?php include 'views/topbar.phtml' ?>
      <?php include 'views/section-video.phtml' ?>
      <?php include 'views/section-overview.phtml' ?>
      <?php include 'views/section-topSlider.phtml' ?>
      <?php include 'views/section-demo.phtml' ?>
      <?php include 'views/section-focus.phtml' ?>
      <?php include 'views/section-samples.phtml' ?>
      <?php include 'views/section-purchase.phtml' ?>
      <?php include 'views/section-social.phtml' ?>
    </div>
    <?php include 'views/section-comments.phtml' ?>
    <?php include 'views/suscribe.phtml' ?>
    <?php include 'views/footer.phtml' ?>
  </body>
</html>