<div id="modal-beta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" data-dismiss="modal" aria-hidden="true" class="close">×</button>
      </div>
      <div class="modal-body">
        <h3>Ahora debes confirmar la suscripción en tu correo</h3>
        <p>En tu buzón de entrada recibirás un correo de Sexy English. Verás un botón para confirmar que quieres unirte a nuestra lista de aspirantes a<i>sexy students</i>;)</p>
      </div>
      <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="boton btn-claro btn btn-primary">Ok, comprendido</button>
      </div>
    </div>
  </div>
</div>