<section class="video">
  <div id="bgVideo" class="background"></div>
  <div class="holder">
    <div class="cont"><span class="sdf"><strong>Startup</strong>Design Framework</span><a href="https://vimeo.com/designmodo/startup" target="_blank" class="play"><span class="fui-play"></span></a><span class="suys"><strong>Suit Up</strong>your
Startup</span><a href="#overview" class="arrow"><span aria-hidden="true" class="icn_arrow"></span></a>
    </div>
  </div>
</section>