<section id="lastBlock-wrapper" class="lastBlock">
  <ul id="lastSlider">
    <li>
      <section class="moreThanImage">
        <div class="holder">
          <div class="bg">
            <div class="pic1 visible"></div>
            <div class="pic2"></div>
            <div class="pic3"></div>
          </div>
          <div class="cont">
            <h1>Objetivos claros</h1>
            <p>Nuestros cursos tienen como objetivo prepararte para superar pruebas de nivel oficiales internacionales.</p>
            <ul>
              <li>
                <h3>Smart Layers</h3>
                <p>Just put the image with your App screen inside Smart Layer and get the photo.</p>
              </li>
              <li>
                <h3>High Resolution</h3>
                <p>We did a 2.5K size photo that will suit even for a very large site.</p>
              </li>
            </ul>
            <div class="anthony">Photos for samples are made by<a href="http://photo.repponen.com/" target="_blank">Anton
Repponen</a>during his travels around the world. Contact him to purchase some photos.</div>
          </div>
        </div>
      </section>
    </li>
    <li>
      <section class="doc">
        <div class="holder">
          <div class="bg">
            <div></div>
          </div>
          <div class="cont">
            <h1>Documentation</h1>
            <p>Documentation is really important for a developer. Right from it you get to know the product. We tried to describe all the components, provide the set-up instructions and foresee most of the issues you may come across while working with the
              framework.
            </p>
            <ul>
              <li>
                <h3>User Guide</h3>
                <p>You’ll get a description of each component and learn how to connect and use them.</p>
              </li>
              <li>
                <h3>Video Tutorials<span class="soon">Soon</span></h3>
                <p>Video tutorials show you how to make a site from design to code.</p>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </li>
    <li>
      <section class="showcase">
        <div class="holder">
          <div class="bg">
            <div class="pic1 visible"></div>
            <div class="pic2"></div>
          </div>
          <div class="cont">
            <h1>Showcase</h1>
            <p>Two perfect examples of using framework - Crumbs and Hipsta Food. These guys have a passion for cooking food and they are really a good deal. We’ll be glad to have a look at your projects created on Startup Framework and show them to our users.</p>
            <ul>
              <li>
                <a href="http://crumbs.am" target="_blank">
                  <img alt="Crumbs" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/bottomSlider/crumbs.png" /><b><strong>Crumbs</strong><span class="svgIcon"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="16" height="16" viewbox="0 0 32 32"><path d="M30 0h-16c-1.105 0-2 0.894-2 2v16c0 1.105 0.895 2 2 2h16c1.105 0 2-0.895 2-2v-16c0-1.105-0.895-2-2-2zM28 16h-12v-12h12v12zM16 28h-12v-12h4v-4h-6c-1.105 0-2 0.895-2 2v16c0 1.105 0.894 2 2 2h16c1.105 0 2-0.895 2-2v-6h-4v4z" fill="#eaeaea"></path></svg></span></b><span>Fresh food, delicious desserts, artisan breads and
cozy atmosphere. All at one place.</span>
                </a>
              </li>
              <li>
                <a href="http://hipstafood.com/" target="_blank">
                  <img alt="Hipstafood" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/bottomSlider/hipstafood.png" /><b><strong>Hipstafood</strong><span class="svgIcon"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="16" height="16" viewbox="0 0 32 32"><path d="M30 0h-16c-1.105 0-2 0.894-2 2v16c0 1.105 0.895 2 2 2h16c1.105 0 2-0.895 2-2v-16c0-1.105-0.895-2-2-2zM28 16h-12v-12h12v12zM16 28h-12v-12h4v-4h-6c-1.105 0-2 0.895-2 2v16c0 1.105 0.894 2 2 2h16c1.105 0 2-0.895 2-2v-6h-4v4z" fill="#eaeaea"></path></svg></span></b><span>Handy
iPhone App preparing for the launch will show you recipes
and teach you to cook.</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </li>
    <li>
      <section class="info">
        <div class="holder">
          <div id="subMenuWrapper">
            <div class="submenu">
              <div></div>
              <ul id="subMenuCtrl">
                <li><span class="selected">Technical
Information</span>
                </li>
                <li><span>Press Release</span>
                </li>
                <li class="faq-u"><span>F.A.Q.</span>
                </li>
              </ul>
            </div>
            <ul id="subMenu">
              <li class="active">
                <div class="cont">
                  <h1>Technical Information</h1>
                  <p>We will be glad to solve your questions. We want to make our product better and very soon we will release some cool updates for you.</p>
                  <div><a href="https://github.com/designmodo/startup-support/issues" target="_blank" class="ask">Ask a Question</a>
                  </div>
                  <dl class="tech-info"><dt>Release Date</dt>
                    <dd class="clearfix">December 16, 2013</dd><dt>Format</dt>
                    <dd class="clearfix">PSD, HTML, CSS, JS, LESS</dd><dt>Size</dt>
                    <dd class="clearfix">637 MB, Zip</dd><dt>Consists</dt>
                    <dd class="clearfix">Components
                      <br/>25 Samples
                      <br/>Photos</dd><dt>Bootstrap Version</dt>
                    <dd class="clearfix">2.3.2</dd><dt>License</dt>
                    <dd class="clearfix"><a href="http://designmodo.com/startup-license" target="_blank">Commercial License</a>
                    </dd><dt>Updates</dt>
                    <dd class="clearfix">Free</dd>
                  </dl>
                </div>
              </li>
              <li>
                <div class="cont">
                  <h1>Press Release</h1>
                  <p>In case you’ve decided to write about our project on your blog you can use this press release. Here you can find all necessary information about Startup Framework: project description, images that you can use while writing articles,
                    and also banners and information about our affiliate program.</p>
                  <p><a href="http://designmodo.com/startup-press-release" target="_blank">Open Press Release</a>
                  </p>
                  <div><a href="mailto:info@designmodo.com?subject=Hello!" class="ask">Contact
Us</a>
                  </div>
                </div>
              </li>
              <li>
                <div class="cont faqiframe">
                  <h1>F.A.Q.</h1>
                  <object data="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/faq.html" type="text/html" width="100%"></object>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </li>
  </ul>
</section>