<section class="demo">
  <div class="holder">
    <div class="background">
      <div></div>
    </div>
    <div class="cont">
      <h1>Demo Version<span class="forksandstars"><iframe frameborder="0" scrolling="0" src="http://ghbtns.com/github-btn.html?user=designmodo&amp;repo=startup-demo&amp;type=watch&amp;count=true&amp;size=large" style="width: 90px; height: 30px; border: none;"><iframe frameborder="0" scrolling="0" src="http://ghbtns.com/github-btn.html?user=designmodo&amp;repo=startup-demo&amp;type=fork&amp;count=true&amp;size=large" style="width: 100px; height: 30px; border: none;"></iframe></iframe></span></h1>
      <p>We have created this demo version in order to show you the structure of Startup Framework. It has some of the components from the full version, 2 great samples and documentation. You can also find 2 images of a Macbook and an iPad, which you can
        use in your project. We hope you will like your first introduction to Startup Framework.
      </p><a href="http://designmodo.github.io/startup-demo" target="_blank" class="button">View
Demo on Github</a>
      <ul>
        <li>
          <h2>What is in this Demo?</h2>
          <p><strong>11</strong>Components</p>
          <p><strong>2</strong>Samples</p>
          <p><strong>2</strong>Pictures</p>
        </li>
        <li>
          <h2>What's in the Full Version?</h2>
          <p><strong>100</strong>Components</p>
          <p><strong>25</strong>Samples</p>
          <p><strong>14</strong>Pictures</p>
        </li>
      </ul>
    </div>
  </div>
</section>