<section class="components">
  <div class="details">
    <div class="cont">
      <h1>Many Useful Components</h1>
      <p>Startup Design Framework contains components and complex blocks which can easily be integrated into almost any design. All of these components are made in the same style, and can easily be integrated into projects, allowing you to create hundreds
        of solutions for your future projects.</p>
    </div>
  </div>
  <div class="holder">
    <ul>
      <li class="first">
        <h3>Responsive Layout</h3>
        <p>Of course we haven’t forgotten about the responsive layout. Create a website with full mobile support.</p>
      </li>
      <li class="second">
        <h3>Clear Grid</h3>
        <p>Components and blocks fixed to common and popular 12 Grid system. It allows you to find understanding between the designer and developer.</p>
      </li>
      <li class="third">
        <h3>Retina Ready</h3>
        <p>Startup Framework works fine on devices supporting Retina Display. Feel the clarity in each pixel.</p>
      </li>
    </ul>
    <div id="component-grid" class="screenshots">
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-1.png" />
      </div>
      <div class="screen double">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-8.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-6.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-8.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-3.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-4.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-7.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-5.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/usefulComponents/img-9.png" />
      </div>
    </div>
  </div>
</section>