<section class="video">
  <div class="fondo-rosa"></div>
  <div id="bgVideo" class="background"></div>
  <div class="holder">
    <div class="container centrador">
      <img src="images/icono.png" alt="" class="icono" />
      <img src="images/logo.png" alt="" />
      <h1>Learn English... Be sexy!</h1><a href="#overview" class="arrow"><span aria-hidden="true" class="icn_arrow"></span></a>
    </div>
  </div>
</section>