<section class="social">
  <div class="holder">
    <div class="container">
      <div class="soc-item google"><a href="https://plus.google.com/110820520056006572902/posts" target="_blank"><span class="name">Google +</span></a>
      </div>
      <div class="soc-item-holder">
        <div class="soc-item twitter"><a href="http://twitter.com/sexyenglish_" target="_blank"><span class="name">Twitter</span></a>
        </div>
        <div class="soc-item facebook"><a href="http://facebook.com/sexyenglishlearning" target="_blank"><span class="name">Facebook</span></a>
        </div>
      </div>
    </div>
  </div>
</section>