<section class="samples">
  <div class="details">
    <div class="cont">
      <h1>Twenty Five Awesome Samples</h1>
      <p>The most important part of the Startup Framework is the samples. The samples form a set of 25 usable pages you can use as is or you can add new blocks from UI Kit. By choosing one of the 25 configurations of the future startup, the process of creation
        is simple and easy.</p>
    </div>
  </div>
  <div class="holder">
    <ul>
      <li class="first">
        <h3>Easy to use</h3>
        <p>To get started, you select the desired sample and base the entire website on it. It’s that simple!</p>
      </li>
      <li class="second">
        <h3>Variety of designs</h3>
        <p>You can decide whether to create your site using UI Kit blocks or samples. The blocks can merge together in various combinations.
        </p>
      </li>
      <li class="third">
        <h3>Feel our design</h3>
        <p>Samples will show you the feeling on how to play around using the components in the website building process.</p>
      </li>
    </ul>
    <div id="samples-grid" class="screenshots">
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-1.png" />
      </div>
      <div class="screen double">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-8.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-22.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-23.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-9.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-17.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-2.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-24.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-10.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-3.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-18.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-25.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-11.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-4.png" />
      </div>
      <div class="screen">img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-19.png" alt="" /></div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-26.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-12.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-5.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-13.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-27.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-20.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-6.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-21.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-14.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-7.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-15.png" />
      </div>
      <div class="screen">
        <img alt="" src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/awesomeSamples/img-16.png" />
      </div>
    </div>
  </div>
</section>