<section id="topSlider-wrapper" class="features">
  <ul id="topSlider">
    <li>
      <section class="first">
        <div class="holder">
          <h1>Beautiful Framework</h1>
          <p>A high-quality solution for those who want to change their startup and not waste too much time.</p>
          <div class="item">
            <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon1.png" class="icon" />
            <h3>Block Model</h3>
            <p>You can easily combine any components in a variety of design projects. It’s easy!</p>
          </div>
          <div class="item">
            <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon2.png" class="icon" />
            <h3>Many Components</h3>
            <p>There are a lot of different components that will help you to make a perfect suit for your startup.</p>
          </div>
        </div>
      </section>
    </li>
  </ul>
</section>