<section id="topSlider-wrapper" class="features">
  <ul id="topSliderCtrl">
    <li><a data-slide-index="0">First</a>
    </li>
    <li><a data-slide-index="1">Second</a>
    </li>
    <li><a data-slide-index="2">Third</a>
    </li>
  </ul>
  <ul id="topSlider">
    <li>
      <section class="first">
        <div class="holder">
          <h1>Beautiful Framework</h1>
          <p>A high-quality solution for those who want to change their startup and not waste too much time.</p>
          <div class="item">
            <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon1.png" class="icon" />
            <h3>Block Model</h3>
            <p>You can easily combine any components in a variety of design projects. It’s easy!</p>
          </div>
          <div class="item">
            <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon2.png" class="icon" />
            <h3>Many Components</h3>
            <p>There are a lot of different components that will help you to make a perfect suit for your startup.</p>
          </div>
        </div>
      </section>
    </li>
    <li>
      <section class="second">
        <div class="holder">
          <h1>Ready to Code</h1>
          <p>Each component is coded for web which will sufficiently fasten the process of creating a website.</p>
          <div class="item">
            <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon3.png" class="icon" />
            <h3>HTML5, CSS3, LESS</h3>
            <p>We used checked-out technologies to give the best results.
            </p>
          </div>
          <div class="item">
            <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon4.png" class="icon" />
            <h3>Based on Bootstrap</h3>
            <p>HTML layout is based on one of the common and reliable frameworks at this time - Bootstrap v 2.3.2.</p>
          </div>
        </div>
      </section>
    </li>
    <li>
      <section class="third">
        <div class="holder">
          <h1>Perfect for Startups</h1>
          <p>Startup Framework will help you to find an awesome form for your startup project in a short time.</p>
          <div class="item">
            <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon5.png" class="icon" />
            <h3>Save Your Time</h3>
            <p>Use your time for generating new ideas for your startup. Take a break from the routine.</p>
          </div>
          <div class="item">
            <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon6.png" class="icon" />
            <h3>Money Economy</h3>
            <p>Startups can save money on design and code and spend it on concept and functionality.</p>
          </div>
        </div>
      </section>
    </li>
  </ul>
</section>