<section id="especificaciones" class="demo">
  <div class="holder">
    <div class="background">
      <div></div>
    </div>
    <div class="cont">
      <h1>Qué incluirá nuestra demo</h1>
      <div class="lista">
        <p> <i class="fa fa-check"></i>Una lección parcial para cada uno de los tres niveles.</p>
        <p> <i class="fa fa-check"></i>Algunos ejercicios de los niveles. Criterios y autocorrección.</p>
        <p> <i class="fa fa-check"></i>Diccionario con vocabulario de inicio</p>
        <p> <i class="fa fa-check"></i>Prueba de nivel gratuita.</p>
        <p> <i class="fa fa-check"></i>Sorteo de 2 skype semanales durante 60 días, entre nuestros alumnos registrados.</p>
        <p> <i class="fa fa-check"></i>Chat de consultas y sugerencias</p>
      </div>
      <ul>
        <li>
          <h2>Paquete silver</h2>
          <p><strong>22</strong>lecciones</p>
          <p><strong>2</strong>tests de evaluación</p>
          <p><strong>1</strong>entrevista personal</p>
        </li>
        <li>
          <h2>Paquete gold</h2>
          <p><strong>22</strong>lecciones</p>
          <p><strong>2</strong>tests de evaluación</p>
          <p><strong>1</strong>test de personalidad en inglés</p>
          <p><strong>1</strong>entrevista personal</p>
          <p><strong>2</strong>clases por skype/mes</p>
        </li>
      </ul>
    </div>
  </div>
</section>