<section id="topSlider-wrapper" class="features">
  <ul id="topSlider">
    <li>
      <section class="first">
        <div class="holder">
          <h1>En tu bolsillo, en tu mano, en tu dormitorio</h1>
          <p>Puedes disfrutar con Sexy English en tu móvil, en tu tablet y en tu ordenador. Lleva Sexy English donde quiera que vayas.</p>
          <div class="item">
            <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon1.png" class="icon" />
            <h3>Aprendizaje 24/7</h3>
            <p>Cualquier momento puede ser un momento Sexy English.</p>
          </div>
          <div class="item">
            <img src="http://designmodo.com/wp-content/themes/designmodov2.1/custom-pages/startup/presentation/img/scrollBlock/Icon2.png" class="icon" />
            <h3>Siempre algo nuevo que descubrir</h3>
            <p>Todos los meses actualizaremos los contenidos con nuevas lecciones, vídeos y estimulantes propuestas.</p>
          </div>
        </div>
      </section>
    </li>
  </ul>
</section>