<section id="lecciones" class="samples">
  <div class="details">
    <div class="cont">
      <h1>Un aprendizaje emocional</h1>
      <p>Hemos diseñado un plan de estudios que te permitirá aprender y explorar el idioma desde un punto de vista emocional. El juego, la seducción, el intercambio de emociones, son la mejor base para el aprendizaje de un idioma.</p>
    </div>
  </div>
  <div class="holder">
    <ul>
      <li class="first">
        <h3>Tres niveles de dificultad</h3>
        <p>Good, better, best. Ajustamos las lecciones según tus conocimientos del idioma.</p>
      </li>
      <li class="second">
        <h3>Objetivos claros</h3>
        <p>Nuestros cursos tienen como objetivo prepararte para superar pruebas de nivel oficiales internacionales.</p>
      </li>
      <li class="third">
        <h3>+18</h3>
        <p>El contenido de nuestro temario está destinado a adultos, por lo que tienes que tener más de 18 años para participar en Sexy English.</p>
      </li>
    </ul>
    <div id="samples-grid" class="screenshots">
      <div class="screen">
        <img alt="" src="images/thumbs/01.png" />
      </div>
      <div class="screen double">
        <img alt="" src="images/thumbs/04.png" />
      </div>
      <div class="screen">
        <img alt="" src="images/thumbs/02.png" />
      </div>
      <div class="screen">
        <img alt="" src="images/thumbs/03.png" />
      </div>
      <div class="screen">
        <img alt="" src="images/thumbs/05.png" />
      </div>
      <div class="screen">
        <img alt="" src="images/thumbs/06.png" />
      </div>
      <div class="screen">
        <img alt="" src="images/thumbs/07.png" />
      </div>
    </div>
  </div>
</section>