<section id="overview" class="simple-block">
  <div class="holder">
    <h1>Hemos inventado</h1>
    <p class="iconos"><i class="fa fa-2x fa-pencil"></i><i class="fa fa-2x fa-tablet"></i><i class="fa fa-2x fa-rocket"></i><i class="fa fa-2x fa-heart-o"></i>
    </p>
    <p>orem ipsum dolor sit amet consequetur adispicit eot ipsum dolor sit amet conse, orem ipsum dolor sit amet consequetur adispicit eot ipsum dolor sit amet conse. Vorem ipsum dolor sit amet consequetur adispicit eot ipsum dolor sit amet conse.</p>
    <div
    class="clear-both"></div>
  </div>
  <img src="images/overview-ipad.png" alt="" class="ipad-fondo" />
</section>