<section id="overview" class="simple-block">
  <div class="holder">
    <h1>Hemos revolucionado...</h1>
    <p class="iconos"><i class="fa fa-2x fa-pencil"></i><i class="fa fa-2x fa-tablet"></i><i class="fa fa-2x fa-rocket"></i><i class="fa fa-2x fa-heart-o"></i>
    </p>
    <p>En Sexy English nos hemos propuesto revolucionar el modo en que aprendes inglés. En nuestro portal aprenderás de una forma totalmente natural, mientras te relajas y das rienda suelta a tus sentidos, disfrutando de todo aquello que te produce placer.</p>
    <div
    class="clear-both"></div>
  </div>
  <img src="images/overview-ipad.png" alt="" class="ipad-fondo" />
</section>