<section class="content-13 subscribe-form bg-turquoise">
  <div class="container">
    <div class="row">
      <form id="mc-embedded-subscribe-form" action="http://bueninvento.us3.list-manage1.com/subscribe/post?u=3810f0a3c717bec4b2463d73a&amp;id=384d876672" method="post" name="mc-embedded-subscribe-form" target="_blank" novalidate="novalidate" class="validate">
        <div class="span8 mc-field-group">
          <input id="theinput" type="text" placeholder="Introduce tu email" spellcheck="false" name="EMAIL" />
        </div>
        <div id="mce-responses" class="clear">
          <div id="mce-error-response" style="display: none;" class="response"></div>
          <div id="mce-success-response" style="display: none;" class="response"></div>
        </div>
        <div style="position: absolute; left: -5000px;">
          <input type="text" name="b_3810f0a3c717bec4b2463d73a_384d876672" value="" />
        </div>
        <div class="span4">
          <button type="submit" name="subscribe" class="btn btn-large btn-primary">Suscríbete</button>
          <div class="btn btn-large btn-primary btn-marron no-thanks">No, gracias</div>
        </div>
      </form>
    </div>
  </div>
</section>