<div id="upper-menu-mobile">
  <div id="page-menu-wrapper">
    <ul style="border: none; box-shadow: none;" class="main no-js">
      <li class="submenu-item mobile-class"><a href="#" class="top-menu"><i class="fa fa-bars"></i></a>
        <div class="dropdown-menu categories">
          <div class="menu-header">
            <ul id="menu-nav-menu-1" class="menu">
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-98952"><a href="#bgVideo">Inicio</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18118"><a href="#overview">Qué es Sexy English</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18124"><a href="#especificaciones">Especificaciones</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-46154"><a href="#lecciones">Lecciones</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18125"><a href="#content-wrapper">Comentarios</a>
              </li>
            </ul>
          </div>
        </div>
      </li>
    </ul>
    <ul class="main right no-js">
      <li class="submenu-item">
        <div class="top-menu show-suscribe">Suscríbete</div>
      </li>
      <li class="submenu-item hidden-xs">
        <a href="javascript:void(0)" class="top-menu">
          <label>Síguenos</label>
        </a>
        <div class="dropdown-menu follow">
          <ul class="social">
            <li><a href="http://www.twitter.com/sexyenglish_" target="_blank" title="Follow us on Twitter" class="twitter">Twitter</a>
            </li>
            <li><a href="http://www.facebook.com/sexyenglishlearning" target="_blank" title="Join us on Facebook" class="facebook">Facebook</a>
            </li>
            <li><a href="https://plus.google.com/110820520056006572902/posts" target="_blank" title="Google+" class="googleplus">Google+</a>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</div>
<div id="upper-menu-container">
  <div id="page-menu-wrapper">
    <ul class="main left no-js">
      <li class="submenu-item mobile-class"><a href="#" class="top-menu"><i class="fa fa-bars"></i></a>
        <div class="dropdown-menu categories">
          <div class="menu-header">
            <ul id="menu-nav-menu-1" class="menu">
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-98952"><a href="#bgVideo">Inicio</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18118"><a href="#overview">Qué es Sexy English</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18124"><a href="#especificaciones">Especificaciones</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-46154"><a href="#lecciones">Lecciones</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18125"><a href="#content-wrapper">Comentarios</a>
              </li>
            </ul>
          </div>
        </div>
      </li>
    </ul>
    <ul style="float: right; right: -1px; position: relative;" class="main right no-js">
      <li class="submenu-item mobile-class">
        <div class="top-menu show-suscribe">Suscríbete</div>
      </li>
      <li class="submenu-item mobile-class"><a href="#" class="top-menu">Síguenos</a>
        <div class="dropdown-menu follow">
          <ul class="social">
            <li><a href="http://www.twitter.com/sexyenglish_" target="_blank" title="Follow us on Twitter" class="twitter">Twitter</a>
            </li>
            <li><a href="http://www.facebook.com/sexyenglishlearning" target="_blank" title="Join us on Facebook" class="facebook">Facebook</a>
            </li>
            <li><a href="https://plus.google.com/110820520056006572902/posts" target="_blank" title="Google+" class="googleplus">Google+</a>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</div>