<div id="upper-menu-mobile">
  <div id="page-menu-wrapper">
    <ul style="border: none; box-shadow: none;" class="main no-js">
      <li class="submenu-item mobile-class"><a href="#" class="top-menu"><i class="fa fa-bars"></i></a>
        <div class="dropdown-menu categories">
          <div class="menu-header">
            <ul id="menu-nav-menu-1" class="menu">
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-98952"><a href="http://designmodo.com/design/">Design</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18118"><a href="http://designmodo.com/freebies/">Freebies</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18124"><a href="http://designmodo.com/tutorials/">Tutorials</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-46154"><a href="http://designmodo.com/coding/">Coding</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18120"><a href="http://designmodo.com/inspiration/">Inspiration</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18125"><a href="http://designmodo.com/wordpress/">WordPress</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-79238"><a href="http://designmodo.com/resources/">Resources</a>
              </li>
            </ul>
          </div>
        </div>
      </li>
    </ul>
    <ul class="main right no-js">
      <li class="submenu-item"><a href="" class="top-menu show-suscribe">Suscríbete</a>
      </li>
      <li class="submenu-item hidden-xs">
        <a href="javascript:void(0)" class="top-menu">
          <label>Síguenos</label>
        </a>
        <div class="dropdown-menu follow">
          <ul class="social">
            <li><a href="http://feeds.feedburner.com/sexyenglish" target="_blank" title="Subscribe by RSS" class="rss">RSS</a>
            </li>
            <li><a href="http://www.twitter.com/sexyenglishlearning" target="_blank" title="Follow us on Twitter" class="twitter">Twitter</a>
            </li>
            <li><a href="http://www.facebook.com/sexyenglishlearning" target="_blank" title="Join us on Facebook" class="facebook">Facebook</a>
            </li>
            <li><a href="https://www.google.com/+sexyenglishlearning" target="_blank" title="Google+" class="googleplus">Google+</a>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</div>
<div id="upper-menu-container">
  <div id="page-menu-wrapper">
    <ul class="main left no-js">
      <li class="submenu-item mobile-class"><a href="#" class="top-menu"><i class="fa fa-bars"></i></a>
        <div class="dropdown-menu categories">
          <div class="menu-header">
            <ul id="menu-nav-menu-1" class="menu">
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-98952"><a href="http://designmodo.com/design/">Design</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18118"><a href="http://designmodo.com/freebies/">Freebies</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18124"><a href="http://designmodo.com/tutorials/">Tutorials</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-46154"><a href="http://designmodo.com/coding/">Coding</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18120"><a href="http://designmodo.com/inspiration/">Inspiration</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-18125"><a href="http://designmodo.com/wordpress/">WordPress</a>
              </li>
              <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-79238"><a href="http://designmodo.com/resources/">Resources</a>
              </li>
            </ul>
          </div>
        </div>
      </li>
    </ul>
    <ul style="float: right; right: -1px; position: relative;" class="main right no-js">
      <li class="submenu-item mobile-class"><a href="" class="top-menu show-suscribe">Suscríbete</a>
      </li>
      <li class="submenu-item mobile-class"><a href="#" class="top-menu">Síguenos</a>
        <div class="dropdown-menu follow">
          <ul class="social">
            <li><a href="http://feeds.feedburner.com/designmodo" target="_blank" title="Subscribe by RSS" class="rss">RSS</a>
            </li>
            <li><a href="http://www.twitter.com/designmodo" target="_blank" title="Follow us on Twitter" class="twitter">Twitter</a>
            </li>
            <li><a href="http://www.facebook.com/designmodo" target="_blank" title="Join us on Facebook" class="facebook">Facebook</a>
            </li>
            <li><a href="https://www.google.com/+DesignModo" target="_blank" title="Google+" class="googleplus">Google+</a>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</div>
<div id="header-wrapper">
  <div id="logo">
    <a href="http://designmodo.com" title="Designmodo – Web Design and Development Magazine" class="main-logo"></a>
  </div>
</div>
<div id="main-wrapper">
  <script type="text/javascript">
  try
  {
    Typekit.load();
  }
  catch (e)
  {}
  </script>
</div>