<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>¿Cómo vamos a aprender?</h3>
      <p>El método parte de la idea de que todos somos adultos, con ganas de vivir y aprender, con intereses propios y ganas de explorar el mundo de las relaciones, las emociones y los sentidos.</p>
      <p>En Sexy English vamos a aprender a construir, pensar, hablar y escuchar en inglés desde nuestros instintos y emociones. Sensualidad, sexualidad, meditación y relajación son nuestros puntos de partida. Contenidos de alto voltaje intelectual, para
        personas especiales.</p>
      <p><b>¿Cuál es nuestro método?</b>
      </p>
      <p>Planteamos un catálogo completo de lecciones, impartidas por profesores nativos. Hemos seleccionado 48 temas que estamos seguros de que te interesarán.</p>
      <p>Escucharás, practicarás, plantearás tus dudas y sugerencias…</p>
      <p>Te recomendamos que hagas una evaluación de partida, con un test tradicional, donde situaremos tu nivel en el estándar europeo. A la finalización del curso, debes realizar tu prueba de evaluación con el fin de conocer tu avance.</p>
      <p>No obstante y si nos sigues, y seguro que lo harás, tu mismo percibirás la mejora continua en tu nivel, porque te comunicarás en inglés y harás tus consultas por escrito, corregirás tus ejercicios y podrás mantener vía Skype con nuestros profesores
        nativos pequeñas conversaciones.</p>
      <p>Entre todos, configuraremos un diccionario propio con palabras nuevas y tradicionales, plantearemos temas del interés de nuestros alumnos y crearemos las lecciones correspondientes. No sólo vas a aprender vocabulario, vas a aprender a hablar y a
        escribir, cosas prácticas, divirtiéndote…</p>
      <p>Entra, prueba y apúntate gratuitamente a nuestra primera lección… son treinta días de aprendizaje… haz consultas, participa, plantea tus intereses…conócenos y decídete.</p>
      <p>A partir de este momento, entras a navegar en inglés, con algún apoyo en español, pero con la voluntad de que en un plazo medio o corto, según tu nivel, el área de alumnos es “vivir en inglés”.</p>
      <div class="btn boton btn-claro">Quiero saber más</div>
    </div>
    <div class="col-md-6">
      <div class="hover-scape">
        <img src="static/img/img-iphone.png" alt="" class="img-iphone" />
        <img src="static/img/img-ipad.png" alt="" class="img-ipad" />
      </div>
    </div>
  </div>
</div>