<div class="container">
  <div class="row">
    <div class="col-md-6">
      <p>Sexy English solo es para adultos mayores de 18 años.</p>
      <p>Aquí podrás acceder al contenido de las lecciones y demás contenido mediante nombre de usuari@ y contraseña en cuanto las colguemos en la web.</p>
      <p>Niveles:</p>
      <p>Basic - Lessons 1-22</p>
      <p>Better - Lessons 23-44</p>
      <p>Best - Lessons 45-66</p>
      <p>Diccionario Sexy</p>
      <p>Nuestros Cuentos</p>
      <p>Tus Cuentos</p>
      <p>Consultas para usuari@s</p>
      <p></p>
      <p>Mientras tanto, ¿quieres saber el temario? Estos son alguno de los temas o entornos en los que vamos a trabajar en inglés:</p>
      <p>Aphrodisiacs How to Excite your Partner Sex and Colours</p>
      <p>Beauty in Unknown Places Hygiene Sex and Music</p>
      <p>Body Language Imperatives Sex Toys</p>
      <p>Brain Power Infidelity Skin Power</p>
      <p>Candles Kisses and Kissing Smiling</p>
      <p>Chimes, Bells and Singing bowls Lingerie Stripping and Nudity</p>
      <p>Clothing Love Songs and Lyrics Toxic Men</p>
      <p>Costumes and Dressing Up Man Hunting Toxic Women</p>
      <p>Dancing Massages Tupper Sex</p>
      <p>Dining and Table Laying Multiorgasms Voice Seduction</p>
      <p>Dirty vs Elegant Phrasing Natural Seduction What Men Don't Like</p>
      <p>Exciting Places Odours and Perfumes What Men Like</p>
      <p>Exciting Romantic Getaways Packing a Weekend Suitcase Wining</p>
      <p>Faking and Frigidity Personality Testing Women Talking About Men</p>
      <p>First Time with Someone New Pillow Talk What's in Women's Handbags?</p>
      <p>Flowers & Flower Language Positions</p>
      <p>Food for Good/Bad Sex Self-Pleasuring</p>
      <div class="btn boton btn-claro">Quiero saber más</div>
    </div>
    <div class="col-md-6">
      <div class="hover-scape">
        <img src="static/img/img-iphone.png" alt="" class="img-iphone" />
        <img src="static/img/img-ipad.png" alt="" class="img-ipad" />
      </div>
    </div>
  </div>
</div>