<div class="container section-01">
  <div class="brand centrador">
    <img src="static/img/icono2.png" width="60" alt="" class="icono display-block centered" />
    <img src="static/img/logo.png" width="350" alt="" class="display-block centered" />
  </div>
  <div class="row">
    <div class="col-md-6">
      <h3>Un método de aprendizaje innovador... y sexy</h3>
      <p>La sensualidad, la sexualidad, las relaciones humanas, el autoconocimiento, la diversión. Todo aquello que te complace está lleno de riquezas a explorar ¿Por qué no hacerlo en inglés?</p>
      <p>Si quieres aprender y mejorar tu inglés, Sexy English es un innovador método de aprendizaje con el que aprenderás, te divertirás y comprobarás tus avances.</p>
      <div class="btn boton btn-claro">Quiero saber más</div>
    </div>
    <div class="col-md-6">
      <div class="hover-scape">
        <img src="static/img/img-ipad.png" alt="" class="img-ipad" />
        <img src="static/img/img-iphone.png" alt="" class="img-iphone" />
      </div>
    </div>
  </div>
</div>