<div class="container section-01">
  <div class="row">
    <div class="col-md-6 col-stretch">
      <div class="brand from-left">
        <img src="static/img/icono2.png" width="60" alt="" class="icono display-block centered" />
        <img src="static/img/logo.png" width="350" alt="" class="display-block centered" />
      </div>
      <div class="contenido from-alpha">
        <h3 class="font">Un método de aprendizaje innovador</h3>
        <p class="font">La sensualidad, la sexualidad, las relaciones humanas, el autoconocimiento, la diversión. Todo aquello que te complace está lleno de riquezas a explorar ¿Por qué no hacerlo en inglés?</p>
        <p class="font">Si quieres aprender y mejorar tu inglés, Sexy English es un innovador método de aprendizaje con el que aprenderás, te divertirás y comprobarás tus avances.</p>
        <div class="btn btn-claro btn-large">Quiero saber más</div>
      </div>
    </div>
    <div class="col-md-6 col-stretch">
      <div class="hover-scape from-right">
        <img src="static/img/img-ipad.png" alt="" class="img-ipad" />
        <img src="static/img/img-iphone.png" alt="" class="img-iphone" />
      </div>
    </div>
  </div>
</div>