<header role="banner" class="navbar navbar-fixed-top bs-docs-nav">
  <div class="container">
    <div class="navbar-header">
      <button type="button" data-toggle="collapse" data-target=".bs-navbar-collapse" class="navbar-toggle"><span class="sr-only"></span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      </button><a href="./" data-0="margin-top:-40px" data-10="margin-top:0" class="navbar-brand">Sexy English</a>
    </div>
    <nav role="navigation" class="collapse navbar-collapse bs-navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="./about">Suscríbete</a>
        </li>
        <li><a href="./about">Síguenos en Facebook</a>
        </li>
      </ul>
    </nav>
  </div>
</header>