<div id="skrollr-body"></div>
<header role="banner" data-0="background-color:rgba(0,0,0,0)" data-250="background-color:rgba(0,0,0,.15)" class="navbar navbar-fixed-top bs-docs-nav">
  <div class="container">
    <div class="navbar-header">
      <a href="./" data-0="opacity:0" data-250="opacity:1" class="navbar-brand">
        <img src="static/img/icono2.png" width="30" alt="" class="icono hidden-xs" />
        <img src="static/img/logo.png" height="50" alt="" class="hidden-xs" />
      </a>
    </div>
    <nav role="navigation">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden-xs"><a href="./about" class="btn btn-alpha">Suscríbete</a>
        </li>
        <li class="hidden-xs"><a href="./about" class="btn btn-alpha">Síguenos en Facebook</a>
        </li>
      </ul>
    </nav>
  </div>
</header>