<header role="banner" data-0="background-color:red" data-10="background-color:blue" class="navbar navbar-inverse navbar-fixed-top bs-docs-nav">
  <div class="container">
    <div class="navbar-header">
      <button type="button" data-toggle="collapse" data-target=".bs-navbar-collapse" class="navbar-toggle"><span class="sr-only"></span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      </button>
    </div>
    <nav role="navigation" class="collapse navbar-collapse bs-navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="./about">Suscríbete</a>
        </li>
        <li><a href="./about">Síguenos en Facebook</a>
        </li>
      </ul>
    </nav>
  </div>
</header>