<meta charset="utf-8" />
<title>Sexy English | Learn English... Be Sexy!</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="Sexy English | Learn english... Be sexy!" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<link rel="canonical" href="http://www.sexy-english.com/" />
<meta name="keywords" content="Sexy english, learn english, aprender inglés, inglés divertido, fun english, skype english" />
<link rel="shortcut icon" href="static/img/favicon.ico" />