<!DOCTYPE html>
<html lang="es">
  <head>
    <?php include 'views/phtml/includes/header.phtml' ?>
  </head>
  <body>
    <?php include 'views/phtml/includes/head.phtml' ?>
    <?php include 'views/phtml/pages/home/modals/suscribed.phtml' ?>
    <?php include 'views/phtml/pages/home/slide-01/index.phtml' ?>
    <?php include 'views/phtml/pages/home/slide-02/index.phtml' ?>
    <?php include 'views/phtml/pages/home/slide-03/index.phtml' ?>
    <?php include 'views/phtml/pages/home/slide-04/index.phtml' ?>
    <?php include 'views/phtml/pages/home/slide-05/index.phtml' ?>
    <?php include 'views/phtml/pages/home/slide-06/index.phtml' ?>
    <?php include 'views/phtml/includes/footer.phtml' ?>
  </body>
</html>